name: Build and Test on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-2019
    strategy:
      matrix:
        configuration:
          - { name: 'Windows_VS2019', targetPlatform: 'x64' }

    env:
      VCPKG_LOCATION: ${{ github.workspace }}\vcpkg
      VCPKG_RESPONSE_FILE: ${{ github.workspace }}\vcpkg-windows.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize vcpkg submodule
        run: git submodule update --init

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: List vcpkg directory
        run: dir .\vcpkg
        shell: cmd

      - name: Show vcpkg-windows.txt
        run: type %VCPKG_RESPONSE_FILE%
        shell: cmd

      - name: Run vcpkg
        run: |
          .\vcpkg\vcpkg.exe install --triplet x64-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli
          set BOOST_ROOT=%VCPKG_LOCATION%\installed\x64-windows
        shell: cmd

      - name: Run CMake with Ninja (Debug)
        run: |
          cmake -S . -B ${{ github.workspace }}/build/${{ matrix.configuration.targetPlatform }}_Debug ^
            -DCMAKE_BUILD_TYPE=Debug ^
            -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_LOCATION }}/scripts/buildsystems/vcpkg.cmake ^
            -DBoost_DIR=${{ env.VCPKG_LOCATION }}/installed/x64-windows/share/boost ^
            -DCPPREST_EXCLUDE_BROTLI=OFF
          cmake --build ${{ github.workspace }}/build/${{ matrix.configuration.targetPlatform }}_Debug --config Debug
        shell: cmd

      - name: Run tests (Debug)
        run: |
          cd ${{ github.workspace }}\build\${{ matrix.configuration.targetPlatform }}_Debug\Release\Binaries
          .\test_runner.exe *testd.dll
        shell: cmd

      - name: Run CMake with Ninja (Release)
        run: |
          cmake -S . -B ${{ github.workspace }}/build/${{ matrix.configuration.targetPlatform }}_Release \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_LOCATION }}/scripts/buildsystems/vcpkg.cmake \
            -DCPPREST_EXCLUDE_BROTLI=OFF
          cmake --build ${{ github.workspace }}/build/${{ matrix.configuration.targetPlatform }}_Release --config Release
        shell: cmd

      - name: Run tests (Release)
        run: |
          cd ${{ github.workspace }}\build\${{ matrix.configuration.targetPlatform }}_Release\Release\Binaries
          .\test_runner.exe *test.dll
        shell: cmd
